/*
 * Copyright 2021 Assured Information Security, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* This file is generated by win_syscall_generator. Do not edit. */
/* Provides get_concrete_handler(WindowsEvent*) so Python receives the correct
 * derived handler type (e.g. NtCreateFile) or None. Typemap must appear before the function. */

/* Ensure the generated .cxx includes full definitions (not just fwd.hh) so method wrappers compile.
 * Use namespaces so SWIG-generated code (which uses unqualified type names) resolves correctly. */
%{
{% for name in nt_exposed %}
#include <introvirt/windows/kernel/nt/syscall/{{ name }}.hh>
{% endfor %}
{% for name in win32k_exposed %}
#include <introvirt/windows/kernel/win32k/syscall/{{ name }}.hh>
{% endfor %}
using namespace introvirt::windows::nt;
using namespace introvirt::windows::win32k;
%}

/* Nt* system calls: %nodefaultctor/dtor so Python never constructs/destructs; ignore inject, *Ptr, unwrapped getters. */
{%- for name in nt_exposed %}
{%- set syscall = ntdata[name] %}
%nodefaultctor introvirt::windows::nt::{{ name }};
%nodefaultdtor introvirt::windows::nt::{{ name }};
{%- if not syscall.get('skip_injector', False) %}
%ignore introvirt::windows::nt::{{ name }}::inject;
{%- endif %}
{%- for arg in syscall.get('signature', []) %}
{%- if arg.get('pointer') %}
%ignore introvirt::windows::nt::{{ name }}::{{ arg.functionName }};
{%- endif %}
{%- if arg.get('type') in swig_ignore_return_types %}
%ignore introvirt::windows::nt::{{ name }}::{{ arg.name }};
{%- endif %}
{%- endfor %}
{%- for method in swig_ignore_method_names %}
%ignore introvirt::windows::nt::{{ name }}::{{ method }};
{%- endfor %}
%include <introvirt/windows/kernel/nt/syscall/{{ name }}.hh>
{%- endfor %}

/* win32k system calls */
{%- for name in win32k_exposed %}
{%- set syscall = user32data[name] %}
%nodefaultctor introvirt::windows::win32k::{{ name }};
%nodefaultdtor introvirt::windows::win32k::{{ name }};
{%- if not syscall.get('skip_injector', False) %}
%ignore introvirt::windows::win32k::{{ name }}::inject;
{%- endif %}
{%- for arg in syscall.get('signature', []) %}
{%- if arg.get('pointer') %}
%ignore introvirt::windows::win32k::{{ name }}::{{ arg.functionName }};
{%- endif %}
{%- if arg.get('type') in swig_ignore_return_types %}
%ignore introvirt::windows::win32k::{{ name }}::{{ arg.name }};
{%- endif %}
{%- endfor %}
{%- for method in swig_ignore_method_names %}
%ignore introvirt::windows::win32k::{{ name }}::{{ method }};
{%- endfor %}
%include <introvirt/windows/kernel/win32k/syscall/{{ name }}.hh>
{%- endfor %}

/* get_concrete_handler returns ConcreteHandlerResult*; convert to concrete Python type or None and free. */
%typemap(out) introvirt::windows::ConcreteHandlerResult * {
  if (!$1) {
    $result = Py_None;
    Py_INCREF(Py_None);
  } else if ($1->ptr == NULL) {
    $result = Py_None;
    Py_INCREF(Py_None);
    delete $1;
  } else {
    switch ($1->index) {
{%- for name in nt_switch %}
    case static_cast<int>(introvirt::windows::SystemCallIndex::{{ name }}):
      $result = SWIG_NewPointerObj($1->ptr, $descriptor(introvirt::windows::nt::{{ name }} *), 0);
      break;
{%- endfor %}
{%- for name in win32k_switch %}
    case static_cast<int>(introvirt::windows::SystemCallIndex::{{ name }}):
      $result = SWIG_NewPointerObj($1->ptr, $descriptor(introvirt::windows::win32k::{{ name }} *), 0);
      break;
{%- endfor %}
    default:
      $result = SWIG_NewPointerObj($1->ptr, $descriptor(introvirt::windows::WindowsSystemCall *), 0);
      break;
    }
    delete $1;
  }
}

%inline %{
namespace introvirt { namespace windows {

struct ConcreteHandlerResult {
    void* ptr;
    int index;
};

/* Return by pointer so SWIG invokes the ConcreteHandlerResult * typemap(out);
 * the typemap converts to a concrete Python type and deletes the pointer. */
ConcreteHandlerResult* get_concrete_handler(const WindowsEvent* e) {
    auto* r = new ConcreteHandlerResult{ nullptr, 0 };
    if (!e) return r;
    auto* h = e->syscall().handler();
    if (!h) return r;
    r->ptr = const_cast<WindowsSystemCall*>(h);
    r->index = static_cast<int>(e->syscall().index());
    return r;
}

}} /* namespace introvirt::windows */
%}
