/*
 * Copyright 2021 Assured Information Security, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* This file is generated by win_syscall_generator. Do not edit. */
/* Provides get_concrete_handler(WindowsEvent*) so Python receives the correct
 * derived handler type (e.g. NtCreateFile) instead of WindowsSystemCall. */

%inline %{
namespace introvirt { namespace windows {

struct ConcreteHandlerResult {
    void* ptr;
    int index;
};

ConcreteHandlerResult get_concrete_handler(const WindowsEvent* e) {
    ConcreteHandlerResult r = { nullptr, 0 };
    if (!e) return r;
    auto* h = e->syscall().handler();
    if (!h) return r;
    r.ptr = const_cast<WindowsSystemCall*>(h);
    r.index = static_cast<int>(e->syscall().index());
    return r;
}

}} /* namespace introvirt::windows */
%}

%typemap(out) introvirt::windows::ConcreteHandlerResult {
  if ($1.ptr == NULL) {
    $result = Py_None;
    Py_INCREF(Py_None);
  } else {
    switch ($1.index) {
{% for name in nt_exposed %}
    case static_cast<int>(introvirt::windows::SystemCallIndex::{{ name }}):
      $result = SWIG_NewPointerObj($1.ptr, $descriptor(introvirt::windows::nt::{{ name }} *), 0);
      break;
{% endfor %}
{% for name in win32k_exposed %}
    case static_cast<int>(introvirt::windows::SystemCallIndex::{{ name }}):
      $result = SWIG_NewPointerObj($1.ptr, $descriptor(introvirt::windows::win32k::{{ name }} *), 0);
      break;
{% endfor %}
    default:
      $result = SWIG_NewPointerObj($1.ptr, $descriptor(introvirt::windows::WindowsSystemCall *), 0);
      break;
    }
  }
}
