"""Python bindings for the IntroVirt VM introspection library."""

from typing import Any, Iterator, List, Optional, overload

# Event type constants
EventType_EVENT_FAST_SYSCALL: int
EventType_EVENT_FAST_SYSCALL_RET: int
EventType_EVENT_SW_INT: int
EventType_EVENT_SW_IRET: int
EventType_EVENT_CR_READ: int
EventType_EVENT_CR_WRITE: int
EventType_EVENT_MSR_READ: int
EventType_EVENT_MSR_WRITE: int
EventType_EVENT_EXCEPTION: int
EventType_EVENT_MEM_ACCESS: int
EventType_EVENT_SINGLE_STEP: int
EventType_EVENT_HYPERCALL: int
EventType_EVENT_REBOOT: int
EventType_EVENT_SHUTDOWN: int
EventType_EVENT_MAX: int
EventType_EVENT_UNKNOWN: int

# FastCallType constants
FastCallType_FASTCALL_SYSCALL: int
FastCallType_FASTCALL_SYSRET: int
FastCallType_FASTCALL_SYSENTER: int
FastCallType_FASTCALL_SYSEXIT: int
FastCallType_FASTCALL_UNKNOWN: int

# OS constants
OS_Unknown: int
OS_Windows: int
OS_Linux: int


class DomainInformation:
    domain_name: str
    domain_id: int

    def __init__(self) -> None: ...


class DomainInformationVector:
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> DomainInformation: ...
    def __iter__(self) -> Iterator[DomainInformation]: ...


class StringSet:
    def add(self, x: str) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...


class EventTaskInformation:
    def pid(self) -> int: ...
    def tid(self) -> int: ...
    def process_name(self) -> str: ...


class SystemCall:
    def name(self) -> str: ...
    def supported(self) -> bool: ...
    def will_return(self) -> bool: ...


class SystemCallEvent:
    def instruction(self) -> int: ...
    def handler(self) -> Optional[SystemCall]: ...
    def name(self) -> str: ...
    def raw_index(self) -> int: ...
    def hook_return(self, enabled: bool) -> None: ...
    def return_address(self) -> int: ...


class SystemCallFilter:
    def mask(self, *args: Any) -> Any: ...
    def enabled(self, *args: Any) -> Any: ...
    def set_32(self, index: int, enabled: bool) -> None: ...
    def set_64(self, index: int, enabled: bool) -> None: ...
    def clear(self) -> None: ...

    def __init__(self) -> None: ...


class Guest:
    def os(self) -> int: ...
    def x64(self) -> bool: ...


class Vcpu:
    def id(self) -> int: ...


class Domain:
    def detect_guest(self) -> bool: ...
    def guest(self) -> Optional[Guest]: ...
    def name(self) -> str: ...
    def id(self) -> int: ...
    def vcpu_count(self) -> int: ...
    def poll(self, callback: "EventCallback") -> None: ...
    def interrupt(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def task_filter(self) -> "TaskFilter": ...
    def system_call_filter(self) -> SystemCallFilter: ...
    def intercept_system_calls(self, enabled: bool) -> None: ...
    def intercept_cr_writes(self, cr: int, enabled: bool) -> None: ...


class Event:
    def vcpu(self) -> Vcpu: ...
    def domain(self) -> Domain: ...
    def type(self) -> int: ...
    def syscall(self) -> Optional[SystemCallEvent]: ...
    def task(self) -> EventTaskInformation: ...
    def os_type(self) -> int: ...
    def id(self) -> int: ...


class EventCallback:
    def process_event(self, event: Event) -> None: ...

    def __init__(self) -> None: ...


class TaskFilter:
    def add_pid(self, pid: int) -> None: ...
    def remove_pid(self, pid: int) -> None: ...
    def add_tid(self, tid: int) -> None: ...
    def remove_tid(self, tid: int) -> None: ...
    def add_name(self, name: str) -> None: ...
    def remove_name(self, name: str) -> None: ...
    def clear(self) -> None: ...
    def matches(self, event: Event) -> bool: ...

    def __init__(self) -> None: ...


class Hypervisor:
    @staticmethod
    def instance() -> "Hypervisor": ...

    @overload
    def attach_domain(self, domain_id: int) -> Domain: ...

    @overload
    def attach_domain(self, domain_name: str) -> Domain: ...

    def get_running_domains(self) -> DomainInformationVector: ...
    def hypervisor_name(self) -> str: ...
    def hypervisor_version(self) -> str: ...
    def hypervisor_patch_version(self) -> str: ...
    def library_name(self) -> str: ...
    def library_version(self) -> str: ...


class WindowsGuest(Guest):
    def default_syscall_filter(self, filter: SystemCallFilter) -> None: ...
    @staticmethod
    def syscall_categories() -> List[str]: ...
    def enable_category(self, category: str, filter: SystemCallFilter) -> None: ...


def WindowsGuest_from_guest(g: Guest) -> Optional[WindowsGuest]: ...


def to_string(*args: Any) -> str: ...


# Exception types
class IntroVirtError(Exception): ...


class NoSuchDomainException(IntroVirtError): ...


class DomainBusyException(IntroVirtError): ...


class UnsupportedHypervisorException(IntroVirtError): ...


class GuestDetectionException(IntroVirtError): ...


class InvalidMethodException(IntroVirtError): ...


class InvalidVcpuException(IntroVirtError): ...


class NotImplementedException(IntroVirtError): ...


class CommandFailedException(IntroVirtError): ...


class BadPhysicalAddressException(IntroVirtError): ...


class VirtualAddressNotPresentException(IntroVirtError): ...
