"""Minimal type stubs for the IntroVirt SWIG bindings.

Used by static type checkers when the generated bindings are not built or installed.
When `../build/python/introvirt.pyi` exists, ty prefers that path (see pyproject.toml).
"""

from __future__ import annotations

from enum import Enum
from typing import Any

class EventType(Enum):
    EVENT_FAST_SYSCALL: EventType
    EVENT_FAST_SYSCALL_RET: EventType
    EVENT_UNKNOWN: EventType

class OS(Enum):
    Unknown: OS
    Windows: OS
    Linux: OS

class SystemCallIndex(Enum):
    NtClose: SystemCallIndex
    NtTerminateProcess: SystemCallIndex

class IntroVirtError(Exception): ...

class NoSuchDomainException(IntroVirtError): ...
class DomainBusyException(IntroVirtError): ...
class UnsupportedHypervisorException(IntroVirtError): ...
class GuestDetectionException(IntroVirtError): ...
class InvalidMethodException(IntroVirtError): ...
class InvalidVcpuException(IntroVirtError): ...
class NotImplementedException(IntroVirtError): ...
class CommandFailedException(IntroVirtError): ...
class BadPhysicalAddressException(IntroVirtError): ...
class VirtualAddressNotPresentException(IntroVirtError): ...
class PeException(IntroVirtError): ...

class NTSTATUS:
    def NT_SUCCESS(self) -> bool: ...

class SystemCall:
    def supported(self) -> bool: ...
    def will_return(self) -> bool: ...

class WindowsSystemCall(SystemCall):
    def index(self) -> int: ...
    def name(self) -> str: ...

class NtSystemCall(WindowsSystemCall):
    def result(self) -> NTSTATUS: ...

class NtTerminateProcess(NtSystemCall):
    def target_pid(self) -> int: ...

class SystemCallEvent:
    def handler(self) -> SystemCall: ...
    def hook_return(self, enabled: bool) -> None: ...
    def name(self) -> str: ...
    def raw_index(self) -> int: ...

class WindowsSystemCallEvent(SystemCallEvent):
    def index(self) -> int: ...

class Event:
    def type(self) -> int: ...
    def vcpu(self) -> Vcpu: ...
    def task(self) -> EventTaskInformation: ...
    def syscall(self) -> SystemCallEvent: ...
    def os_type(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...

class WindowsEvent(Event): ...

class EventTaskInformation:
    def pid(self) -> int: ...
    def tid(self) -> int: ...
    def process_name(self) -> str: ...

class WindowsEventTaskInformation(EventTaskInformation):
    def pcr(self) -> KPCR: ...

class KPCR: ...

class Vcpu:
    def id(self) -> int: ...

class EventCallback:
    def process_event(self, event: Event) -> None: ...

class Hypervisor:
    @staticmethod
    def instance() -> Hypervisor: ...
    def attach_domain(self, domain_id: int | str) -> Domain: ...
    def get_running_domains(self) -> list[Any]: ...
    def hypervisor_name(self) -> str: ...
    def hypervisor_version(self) -> str: ...
    def hypervisor_patch_version(self) -> str: ...
    def library_name(self) -> str: ...
    def library_version(self) -> str: ...

class Domain:
    def detect_guest(self) -> bool: ...
    def guest(self) -> Guest: ...
    def interrupt(self) -> None: ...
    def poll(self, callback: EventCallback) -> None: ...
    def system_call_filter(self) -> SystemCallFilter: ...
    def task_filter(self) -> TaskFilter: ...
    def intercept_system_calls(self, enabled: bool) -> None: ...
    def intercept_cr_writes(self, cr: int, enabled: bool) -> None: ...

class Guest:
    def os(self) -> int: ...

class WindowsGuest(Guest):
    def syscall_categories(self) -> tuple[str, ...]: ...
    def default_syscall_filter(self, filter: SystemCallFilter) -> None: ...
    def enable_category(self, category: str, filter: SystemCallFilter) -> None: ...
    def set_system_call_filter(self, filter: SystemCallFilter, index: int, value: bool) -> None: ...

class SystemCallFilter:
    def clear(self) -> None: ...
    def enabled(self, enabled: bool | None = ...) -> bool: ...

class TaskFilter:
    def add_name(self, name: str) -> None: ...
    def add_pid(self, pid: int) -> None: ...
    def add_tid(self, tid: int) -> None: ...
    def clear(self) -> None: ...
    def remove_name(self, name: str) -> None: ...
    def remove_pid(self, pid: int) -> None: ...
    def remove_tid(self, tid: int) -> None: ...

def system_call_from_string(name: str) -> int: ...
def get_windows_syscall_result_value(event: WindowsEvent) -> tuple[bool, int]: ...
def ntstatus_to_string(value: int) -> str: ...
def get_concrete_handler(event: WindowsEvent) -> WindowsSystemCall | None: ...
def WindowsEvent_from_event(event: Event) -> WindowsEvent | None: ...
def WindowsGuest_from_guest(guest: Guest | None) -> WindowsGuest | None: ...
def nt_success(code: int) -> bool: ...
def nt_error(code: int) -> bool: ...
